version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: libra-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - libra-network

volumes:
  postgres_data:

networks:
  libra-network:
    driver: bridge
