### 获取主页
get http://localhost:3000/

### getHello
get http://localhost:3000/test/string

### get json
get http://localhost:3000/test/json

### 获取查询参数
get http://localhost:3000/test/query?name=John&age=30

### 获取路径参数
get http://localhost:3000/test/param/123

### 字符串参数
get http://localhost:3000/test/param/string
### 获取请求体
post http://localhost:3000/test/body http/2
content-type: application/json

{
  "name": "John",
  "age": 30
}

### 获取请求头
get http://localhost:3000/test/header

### 获取请求IP
get http://localhost:3000/test/ip

### 获取主机参数
get http://localhost:3000/test/hostParam

### Patch 请求
patch http://localhost:3000/test/patch

### Put 请求
put http://localhost:3000/test/put

### Delete 请求
delete http://localhost:3000/test/delete

### 路由通配符
get http://localhost:3000/test/ab_cd

### 路由通配符
get http://localhost:3000/test/abdcd

### 状态码
get http://localhost:3000/test/status

### 设置响应头
get http://localhost:3000/test/header

### 重定向
get http://localhost:3000/test/redirect

### 抛出异常
get http://localhost:3000/test/exception

### 分页
get http://localhost:3000/test/pagination?page=1&limit=2

### local认证
post http://localhost:3000/auth/login
content-type: application/json

{
  "username": "superadmin",
  "password": "123456"
}

### get profile
get http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTczNTgxMDY2MiwiZXhwIjoxNzM1ODk3MDYyfQ.Mvf6W4e5a1kHHIkGZdR6ULR9wIGxJ7JW90ndqj-XtMU

### 获取所有用户
get http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoic3VwZXJhZG1pbiIsImlhdCI6MTczNjEzMzE3MCwiZXhwIjoxNzM2MTMzMjAwfQ.3tXEjhAq-r4ie3R9t8PT49k5IG6jMCx8xGxDwn5cEiw

### refresh
post http://localhost:3000/auth/refresh
content-type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImlhdCI6MTczNjEzMzExMCwiZXhwIjoxNzM2MjE5NTEwfQ.Z9JyVVuZFNox7ITweh8ElmqY0RZE1OY-2lPUibTRzTs"
}

### 获取图形验证码
get http://localhost:3000/auth/captcha